version: "3.8"

services:
  postgres:
    image: postgres:11
    env_file: .env.development
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "54432:5432"

  django:
    build:
      context: .
      dockerfile: Dockerfile.django
    env_file: .env.development
    volumes:
      - ./src:/app
    ports:
      - "8080:8080"
    depends_on:
      - "postgres"
    command: ["./wait-for-it.sh", "postgres:5432", "--", "bash", "startup.sh"]

volumes:
  pgdata:
